services:
  postgres:
    image: postgres:14-alpine
    container_name: pg14-retailer-api
    ports:
      - 5432:5432
    volumes:
      - /home/bernd/pg14/data/retailer:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=retailer
      - POSTGRES_USER=retailer
      - POSTGRES_DB=retailer_api
