CREATE OR REPLACE FUNCTION PUBLIC.GET_ALL_RETAILERS()
RETURNS TABLE (
  V_ID INTEGER,
  V_GSTIN TEXT,
  V_BUSINESS_NAME TEXT,
  V_CONTACT_PERSON TEXT,
  V_CONTACT_NUMBER INTEGER,
  V_CONTACT_ADDRESS TEXT,
  V_CONTACT_EMAIL_ID TEXT,
  V_STATUS TEXT,
  V_OUTLET_LIMIT INTEGER
)
LANGUAGE 'plpgsql'

AS
$BODY$
BEGIN
RETURN QUERY
  SELECT * FROM PUBLIC."Retailers";
END;
$BODY$;

ALTER FUNCTION PUBLIC.GET_ALL_RETAILERS() OWNER TO retailer;
