{application,mime,
             [{config_mtime,1718550489},
              {compile_env,[{mime,[types],error}]},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"A MIME type module for Elixir"},
              {modules,['Elixir.MIME']},
              {registered,[]},
              {vsn,"2.0.2"},
              {env,[]}]}.
