[package]
name = "rocket-redis"
version = "0.1.0"
authors = ["Bernd Malle <bernd.malle@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
# rocket_codegen = "0.4.2"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["redis_pool"]
